### ISSUE TITLE
Uncaught Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by sultan99** [lexcast/screen-recorder#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [screen-recorder](https://github.com/lexcast/screen-recorder) package 1.4.0

### Stack Trace

Uncaught Error: Cannot find ffmpeg

```
At C:\Users\sarziyev\.atom\packages\screen-recorder\lib\recorder-manager.coffee:44

Error: Cannot find ffmpeg
    at /packages/screen-recorder/node_modules/fluent-ffmpeg/lib/processor.js:136:22
    at /packages/screen-recorder/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at /packages/screen-recorder/node_modules/fluent-ffmpeg/lib/capabilities.js:116:11
    at /packages/screen-recorder/node_modules/fluent-ffmpeg/lib/utils.js:223:16
    at /packages/screen-recorder/node_modules/which/which.js:68:16)
    at /packages/screen-recorder/node_modules/which/which.js:80:29)
    at /packages/screen-recorder/node_modules/which/which.js:89:16
    at /packages/screen-recorder/node_modules/isexe/index.js:42:5
    at /packages/screen-recorder/node_modules/isexe/windows.js:36:5
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -1:09.5.0 intentions:highlight (input.hidden-input)
  7x -1:09.1.0 core:undo (input.hidden-input)
     -0:24.9.0 intentions:highlight (input.hidden-input)
     -0:23.4.0 screen-recorder:open-select-area (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
autocomplete-modules 1.7.0 
busy-signal 1.4.3 
double-tag 0.9.0 
emmet 2.4.3 
file-icons 2.1.11 
git-blame 1.2.2 
highlight-selected 0.13.1 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-linter 2.0.2 
minimap-split-diff 0.3.7 
package-sync 1.1.0 
rest-client 1.3.1 
screen-recorder 1.4.0 
sort-lines 0.15.0 
split-diff 1.5.1 
```

**Comment by lexcast** [comment]
Hi @sultan99 
Did you install ImageMagick? https://github.com/lexcast/screen-recorder#windows

**Comment by sultan99** [comment]
@lexcast  no 😁
My fault never read instructions.
