### ISSUE TITLE
screen-recorder fails when env. variable $DISPLAY is not ":0".

### ISSUE THREAD

**Issue by akukuq** [lexcast/screen-recorder#13]
### Steps to reproduce:

1. Have atom and screen-recorder installed.
2. Have your $DISPLAY environment variable equal to something else than ":0". (I am not sure what this means and how to change it. For explanation, see below.)
3. Start the screen-recorder by using any of the possible options (record window, active pane, select area).

I am not sure, but it seems that this relates to the number assigned to my display in the environment. See this [forum thread](https://www.linuxquestions.org/questions/linux-desktop-74/ffmpeg-fails-cannot-open-display-0-0-error-1-a-4175613512/). Despite the fact that I only have (and only ever had) a single screen attached to my computer, $DISPLAY is set to ":1" in my environment:
```
$ echo $DISPLAY
:1
```
The error message suggests that ffmpeg fails because it has been called with display=":0" which simply does not exist. I tried changing $DISPLAY to ":0" and starting atom, but this happens:
```
$ export DISPLAY=":0"
$ atom
Invalid MIT-MAGIC-COOKIE-1 key
(atom:7927): Gtk-WARNING **: 16:40:01.111: cannot open display: :0
```
which makes sense, because the display is actually identified as ":1".

### Possible solution:
Add detection of the DISPLAY environment variable and replace ":0" in this line:
https://github.com/lexcast/screen-recorder/blob/76c7813b60a41c56decbb10ae573aaae4fa957b3/lib/adapters/linux.coffee#L9

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Ubuntu 18.04.1
**Thrown From**: [screen-recorder](https://github.com/lexcast/screen-recorder) package 1.5.0

### Stack Trace

Uncaught Error: ffmpeg exited with code 1: Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x55a1653539a0] **Cannot open display :0**.0 257,368, error 1.
:0.0 257,368: Input/output error

```
At /home/user/.atom/packages/screen-recorder/lib/recorder-manager.coffee:45

Error: ffmpeg exited with code 1: Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x55a1653539a0] Cannot open display :0.0 257,368, error 1.
:0.0 257,368: Input/output error

    at /packages/screen-recorder/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -9:58.6.0 core:delete (input.hidden-input)
  4x -9:52.5.0 core:undo (input.hidden-input)
     -9:49.8.0 core:delete (input.hidden-input)
  2x -5:10.9.0 core:backspace (input.hidden-input)
  2x -3:29.5.0 core:delete (input.hidden-input)
     -2:41.9.0 command-palette:toggle (div.package-detail.panels-item)
  2x -2:37.8.0 core:move-down (input.hidden-input)
     -2:36.2.0 core:confirm (input.hidden-input)
     -2:36.2.0 screen-recorder:open-select-area (div.package-detail.panels-item)
  4x -0:51 core:backspace (input.hidden-input)
     -0:10.9.0 command-palette:toggle (div.package-detail.panels-item)
  2x -0:09.1.0 core:move-down (input.hidden-input)
  2x -0:08.1.0 core:move-up (input.hidden-input)
  6x -0:06.8.0 core:move-down (input.hidden-input)
     -0:04.8.0 core:confirm (input.hidden-input)
     -0:04.8.0 screen-recorder:record-active-pane (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
file-icons 2.1.25 
hidpi 0.14.0 
ide-python 1.0.0 
language-matlab 0.2.1 
language-matlab-octave 0.3.0 
screen-recorder 1.5.0 
script 3.18.1 
```

**Comment by akukuq** [comment]
It seems that this is the same issue as in #2 .
