### ISSUE TITLE
Uncaught Error: ffmpeg exited with code 3221225477: 

### ISSUE THREAD

**Issue by hiAndrewQuinn** [lexcast/screen-recorder#14]
[Enter steps to reproduce:]

1. Install [ImageMagick-7.0.8-56-Q16-x64-dll.exe](https://imagemagick.org/script/download.php), checked off "Install ffmpeg", and otherwise stuck to the defaults.
2. Close and reopen Atom.
3. Try `Alt+Shift+D` to Record Active Pane, or `Alt+Shift+W` to Record Window, to see the error in action.

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [screen-recorder](https://github.com/lexcast/screen-recorder) package 1.5.0

### Stack Trace

Uncaught Error: ffmpeg exited with code 3221225477: 

```
At C:\Users\Andre\.atom\packages\screen-recorder\lib\recorder-manager.coffee:45

Error: ffmpeg exited with code 3221225477: 
    at /packages/screen-recorder/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

### Commands

```
     -1:47 pane:show-next-recently-used-item (input.hidden-input)
     -1:46.9.0 pane:move-active-item-to-top-of-stack (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -1:45.9.0 pane:show-previous-recently-used-item (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
     -1:45.3.0 pane:move-active-item-to-top-of-stack (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
 29x -1:42.8.0 core:move-down (input.hidden-input)
 19x -1:41.2.0 core:move-up (input.hidden-input)
     -1:39.4.0 hey-pane:toggle-focus-of-active-pane (input.hidden-input)
     -1:32.1.0 screen-recorder:record-active-pane (input.hidden-input)
     -0:30.8.0 command-palette:toggle (input.hidden-input)
     -0:28.1.0 core:confirm (input.hidden-input)
     -0:28.1.0 screen-recorder:record-window (input.hidden-input)
     -0:22.4.0 core:save (input.hidden-input)
     -0:21.3.0 command-palette:toggle (input.hidden-input)
     -0:14.1.0 screen-recorder:record-active-pane (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.17 
center-cursor 0.4.0 
file-icons 2.1.33 
hey-pane 1.1.2 
highlight-selected 0.16.0 
indent-detective 0.3.3 
ink 0.10.11 
julia-client 0.8.10 
language-batchfile 0.7.5 
language-julia 0.19.1 
latex-completions 0.3.6 
minimap 4.29.9 
open-recent 5.0.0 
project-manager 3.3.7 
screen-recorder 1.5.0 
scroll-through-time 0.3.1 
sort-lines 0.19.0 
todo-show 2.3.2 
tool-bar 1.1.12 
uber-juno 0.2.0 
```

**Comment by hiAndrewQuinn** [comment]
I tried uninstalling ImageMagick, and reinstalling both that and ffmpeg using Chocolatey commands:

```
choco install imagemagick
choco install ffmpeg
```

I got the same issue. 😿

**Comment by hiAndrewQuinn** [comment]
Doing some [digging](https://stackoverflow.com/questions/38419321/c-process-exited-with-error-code-3221225477) reveals that **error code 3221225477 is usually an invalid memory-style error**. So the issue most likely lies with FFmpeg, not with this. Closing.
