### ISSUE TITLE
Uncaught Error: ffmpeg exited with code 1: Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x1ac4420] Ca...

### ISSUE THREAD

**Issue by jaunkst** [lexcast/screen-recorder#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 16.04
**Thrown From**: [screen-recorder](https://github.com/lexcast/screen-recorder) package, v1.2.0

### Stack Trace

Uncaught Error: ffmpeg exited with code 1: Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x1ac4420] Cannot open display :0.0 274,307, error 1.
:0.0 274,307: Input/output error

```
At /home/jaunkst/.atom/packages/screen-recorder/lib/recorder-manager.coffee:44

Error: ffmpeg exited with code 1: Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x1ac4420] Cannot open display :0.0 274,307, error 1.
:0.0 274,307: Input/output error

    at ChildProcess.<anonymous> (/home/jaunkst/.atom/packages/screen-recorder/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -1:30 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:28.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.4.0 screen-recorder:record-window (atom-text-editor.editor)
     -0:02.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 screen-recorder:record-window (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-babel"
    ],
    "packagesWithKeymapsDisabled": [
      "lebab-autocorrect"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
atom-jade, v0.3.0
atom-typescript, v8.9.1
lebab-convert, v0.0.0
linter, v1.11.4
linter-eslint, v7.2.1
linter-jade, v0.3.2
linter-rubocop, v0.4.7
screen-recorder, v1.2.0

# Dev
No dev packages
```

**Comment by lexcast** [comment]
@jaunkst sorry for the delay, how can be this reproduced?

**Comment by iameronmosele** [comment]
I have this problem too
