### ISSUE TITLE
Uncaught Error: Command failed: Invalid Parameter - 0

### ISSUE THREAD

**Issue by FluidCoding** [lexcast/screen-recorder#8]
Throws error when I stop recording. Windows7: Imagemagick/ffmpeg installed. path verified.
cursor blinks and cpu usage increases when I 'start' so I assume it is.

halp

[Enter steps to reproduce:]

1. Start Recording
2. Stop Recording ( Shift + Alt + Z ) 

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [screen-recorder](https://github.com/lexcast/screen-recorder) package 1.2.3

### Stack Trace

Uncaught Error: Command failed: Invalid Parameter - 0

```
At \.atom\packages\screen-recorder\lib\recorder-manager.coffee:80

Error: Command failed: Invalid Parameter - 0

    at /packages/screen-recorder/node_modules/imagemagick/imagemagick.js:88:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -1:36.2.0 snippets:next-tab-stop (input.hidden-input)
     -1:34.8.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:34.8.0 editor:newline (input.hidden-input)
     -1:33.1.0 screen-recorder:stop-recording (input.hidden-input)
     -1:30.8.0 screen-recorder:cancel-recording (input.hidden-input)
     -1:17.7.0 core:delete (input.hidden-input)
     -1:14.3.0 screen-recorder:record-active-pane (input.hidden-input)
     -1:06.6.0 screen-recorder:cancel-recording (input.hidden-input)
     -0:58.5.0 core:backspace (input.hidden-input)
     -0:52.7.0 screen-recorder:record-window (input.hidden-input)
     -0:49.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:49.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:46.4.0 snippets:next-tab-stop (input.hidden-input)
     -0:44.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:44.4.0 editor:newline (input.hidden-input)
     -0:41.6.0 screen-recorder:stop-recording (input.hidden-input)
```

**Comment by danielocdh** [comment]
Same issue since I started using atom on windows 10 around a year ago, is there an alternative to this package?
